### ISSUE TITLE
Felesleges branch törlése

### ISSUE THREAD

**Issue by bimlas** [WagZol/u3eBattleship#1]
A [Zoli branch](https://github.com/WagZol/u3eBattleship/tree/Zoli)-ot törölheted, a [master](https://github.com/WagZol/u3eBattleship/tree/master)-en van a valódi kódod:

![ksnip_20190916-122641](https://user-images.githubusercontent.com/7034200/64951191-8f684e00-d87d-11e9-871d-9d4d9b0b62cb.png)

![ksnip_20190916-122728](https://user-images.githubusercontent.com/7034200/64951196-92fbd500-d87d-11e9-801d-3abb2768eb93.png)

**Comment by WagZol** [comment]
A default branchot ahogy emailben írtad megváltoztattam a master-re és így ki tudtam törölni a Zoli branch-ot. Még otthonról push-olom az újabb repom(melóhelyről tűzfal megfogja) és ha minden ugyan így marad akkor lezárom ezt az issue-t
