### ISSUE TITLE
Szabad koordináták

### ISSUE THREAD

**Issue by WagZol** [WagZol/u3eBattleship#4]
Egy újabb dilemmával találkoztam, nem komoly de jól jönne a tanács.

Ugye a gép úgy választ kurzor koordinátát(ami a hajó kezdő koordinátája) hogy megszerzi a szabad koordinátákat, kisorsol 1-et és megnézi azon a koordinátán van egy olyan irány amin letegyen hajót. Ha nincs akkor ezt a koordinátát kiveszi a szabad koordináták listából és egy másikkal újra próbálkozik.

Szerintem a számítási időn sokat spórolna ha a hajó letevéskor a szabad koordináták listából kivennénk azokat amire a hajó le lett téve illetve az aurája amin van, de a gond ezzel a következő:
-Így a csatatér 2 collection-t tartalmazna. egyfelől önmagát, egyfelől a szabad koordinátákat, ezért kicsit otrombának érzem(így volt annó megoldva
-Nehéz benne keresni mert a conatins nem megy egy olyan kollekción ami kollekciókat tartalmaz, mert a contains arra viszgál hogy a lista belső eleme==az összehasonlító elemekkel. Ezzel az a baj hogy a tömb(2 elemű int tömb a koordinátánk) referencia értéke látszik ilyenkor, és  azok nem fognak megegyezni amikor a letett hajó koordinátáit ki akarom szűrni csak az értékük. Tehát végig kell menni az alap kollekción streammel, allMatch() és Arrays.equals-al összehasonlítítani minden elemet, miközben végigiterálok a hajó koordinátáin

A másik megoldás az hogy kidolgozok egy metódust ami megkeresi a szabad koordinátákat, az alapján hogy hol nincs String. Ezzel a gond:
-Ha az aurát nem tüntetem fel a Board-on akkor sok esetben olyan koordinátákra is rá fog próbálni ami az aura miatt esélytelen hogy jó legyen

Mi  véleményed?
-Külön kollekcót tartalmazzon a Board a szabad koordinátákról, amit hajóletevéskor csökkentünk a letenni kívánt hajó+annak aurájával
-Külön metódust tartalmazzon a Board ami kiszámolja a szabad koordinátákat a már meglévő Boardból?

**Comment by bimlas** [comment]
Külön kollekció legyen, fogd fel úgy, mint egy cache.

Amit a telóban beszéltünk (Ship.clone), azt szerintem máshogy nem lehet, csak deep clone-nal. Próbáltam beröffenteni egy Java projektet és abban létrehozni egy alap tesztet, de bakter, nem jöttem rá, hogy kell. :D Eltelt vele az idő és semmit se tudtam kipróbálni.

Amit meg akartam nézni az az, hogy miként lehetne a deepcopy-t megvalósítani. Itt [van egy jó leírás](https://howtodoinjava.com/java/collections/arraylist/arraylist-clone-deep-copy/), csak épp nem tudtam kipróbálni. Mivel olyan nagyon sok mindene nincs a Ship-nek a koordinátáin kívül, így talán annyira nem vészes a dolog (milye lesz még? színe, texturája?). Max nézd vissza a Builder pattern-t, hogy ott miként oldották meg, mert ott is deep copy-kat kell használni.

**Comment by bimlas** [comment]
... bocs, rosszul emlékeztem, ott saját magát adja vissza. A Prototype mintában használnak deepcopy-t (igény szerint).

**Comment by WagZol** [comment]
Bocs a kötődésért de a deep copy enm ennek az issue-nak a témája!XD az a forgatáshoz kellett, ez viszont szabad koordináták kiválasztása. Nem kötődni akarok de próbálom kihasználni és megismerni az ilyen rendezett munkát(alapból kaotikus vagyok és szeretnék szakítani ezzel a hagyománnyal, de ahhoz meg kell ismerenm hogy mivel ad többet ha minden kommunikáció pl itt a Giten zajlik rendezett formában

Amit linkeltél ott a 3.2. Deep copy of Java collection alrész egész jó ötletet adott hogy szebben meg tudjam oldani a deepclone-t(iterátorral)

A külön gyüjteményben még nem győztél meg:D Az a gond hogy úgy érzem 2 kollekciót tartunk fenn holott 1 is elég lenne. 

Pl.: ha egy hajó úgy néz ki:

```
 AAAA 
 AxxA 
 AAAA 
```
Akkor ebből ki tudom szűrni hogy rohanjon át egy iterálással a String tömbön és ahol üres területet talál annak szedje ki a koordinátáit

Ez a megoldás szebbnek tűnik de minden hajó letevésnél egyszer át kell szkennelnie a táblát

A Cache meg...nem tudom, győzz meg:D Tényleg az zavar hogy külön egy táblát futtatok vmiről ami az alap táblából is kiolvasható csak kicsit lassabban

**Comment by WagZol** [comment]
A Fenti példában az 'x' a hajó az 'A' az aura

**Comment by bimlas** [comment]
Szerintem azért nem lenne rossz a cache (bár én se szeretem, mert olyan "rugalmatlannak" hat), mert így minden hajóletevés előtt ki kell számolnod azt, amit már korábban is. Pl. minden hajóletevés azzal járna, hogy a cache táblából kivonja a hajó és aurája koordinátáit, így azt valójában nem is kellene számolgatni, elég lenne csak megnézni, hogy mik maradtak benne.

**Comment by WagZol** [comment]
Végül a cache mellett döntöttem, szóval ez az issue lezárulhat
